name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call reusable workflow
        uses: ./.github/workflows/sha-short.yml
        with:
          repository: ${{ github.repository }}

      - name: Reusable output
        run: echo ${{ steps.sha_short.outputs.sha_short }}
