name: Call Reusable Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call_reusable:
    uses: ./.github/workflows/sha-short.yml
  test_output:
    needs: call_reusable
    runs-on: ubuntu-latest
    steps:
      - id: result
        run: |
          echo "sha-short result: ${{ needs.call_reusable.outputs.short-sha }}"
