name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: Enter a branch name
        type: string
  push:
    branches:
      - main

jobs:
  call_reusable:
    uses: ./.github/workflows/sha-short.yml
    with:
      sha-length: 8
      branch: main
  test_output:
    needs: call_reusable
    runs-on: ubuntu-latest
    steps:
      - id: result
        run: |
          echo "sha-short result: ${{ needs.call_reusable.outputs.short-sha }}"
