name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      result-length:
        description: the length of the result
        type: number
        required: false
        default: 7
      branch-name:
        description: Enter a branch name
        type: string
        required: false
  push:
    branches:
      - main

jobs:
  call_reusable:
    uses: ./.github/workflows/sha-short.yml
    with:
      sha-length: ${{ inputs.result-length }}
      branch: ${{ inputs.branch-name }}
  test_output:
    needs: call_reusable
    runs-on: ubuntu-latest
    steps:
      - id: result
        run: |
          echo "sha-short result: ${{ needs.call_reusable.outputs.short-sha }}"
