name: Commit and Push Changes

on:
  push:
    branches:
      - main

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          echo "Änderungen vornehmen" >> datei.txt

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Automatischer Commit durch GitHub Actions"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
