name: Commit and Push Changes

on:
  push:
    branches:
      - main

jobs:
  commit-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          cd .github/workflows
          printf "# Latest Versions \n" > README.md
          printf "| Workflow | Hash | Full Path |\n" >> README.md
          printf "| :-- | :-- | :-- |\n" >> README.md
          for rev in $(ls . -I README.md -I create-readme.yml ); do
            hash=$(git rev-list --all --max-count=1 $rev)
            printf "| $rev | $hash | felamanagementag/fela-tools/.github/workflows/$ref@$hash |\n" >> README.md
          done

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Automatischer Commit durch GitHub Actions"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
