name: Create Versions/Hash Readme

on:
  push:
    branches:
      - main
      - develop

jobs:
  create-readme:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create
        run: |
          cd .github/workflows
          printf "# Latest Versions \n" > README.md
          printf "| Workflow | Hash | Full Path |\n" >> README.md
          printf "| :-- | :-- | :-- |\n" >> README.md
          for rev in $(ls . -I README.md -I create-readme.yml ); do
            hash=$(git rev-list --all --max-count=1 $rev)
            printf "| $rev | $hash | felamanagementag/fela-tools/.github/workflows/$ref@$hash |\n" >> README.md
          done
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: Workflow-Version-Overview
          path: .github/workflows/README.md
      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url --push origin https://EstartuPrime:$GITHUB_TOKEN@github.com/your/repo
          git add --all
          git commit -m "Update Workflow Versions" || echo "No changes to commit"
          git push
