name: Create Workflow Latest Hash Readme

on:
  push:
    branches:
      - main

env:
  OUT_FILENAME: "REUSABLE_WORKFLOW_VERSIONS.md"

jobs:
  create-readme:
    permissions: 
      actions: write
      contents: write
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # fetch-depth 0 is important to get the full history, and so we get the real last commit hash, otherwise all are at the same.
          fetch-depth: 0

      - name: Create File
        run: |
          printf "# Latest Versions \n" > ${{ env.OUT_FILENAME }}
          printf "| Workflow | Hash | Full Path |\n" >> ${{ env.OUT_FILENAME }}
          printf "| :-- | :-- | :-- |\n" >> ${{ env.OUT_FILENAME }}
          for rev in $(ls .github/workflows -I create-last-hashes.yml ); do
            hash=$(git rev-list --all --max-count=1 .github/workflows/$rev)
            printf "| $rev | $hash | ${{ github.repository }}/.github/workflows/$rev@$hash |\n" >> ${{ env.OUT_FILENAME }}
          done

      - name: Show File
        run: cat ${{ env.OUT_FILENAME }}
  
      - name: Setup Git & Commit
        run: |
          git config --global user.name 'GitHub Actions [bot]'
          git config --global user.email 'github-actions[bot]@github.com'
          git add .
          git commit -m "Update Workflow Versions" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
