name: Hello world

on:
  workflow_dispatch:
    inputs:
      build-target:
        description: 'The target stage in docker build, "production" is the build-stage.'
        required: true
        # on develop branch we use as default 'production'; For releases we should use 'demo' and push this release to a server that can host the fela-webcore-demo.
        default: "demo"
        type: choice
        options:
          - demo
          - production
          - frontend
          - backend
          - share

env:
  SOME_ENV: 1
  ANOTHER_ENV: Hi

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world"

      - name: With output
        id: set-suffix
        run: |
          echo "image-suffix=$([ '${{ github.event.inputs.build-target }}' != 'production' ] && echo '-${{ github.event.inputs.build-target }}' )" >> $GITHUB_OUTPUT
          echo "image-suffix=$([ '${{ github.event.inputs.build-target }}' != 'production' ] && echo '-${{ github.event.inputs.build-target }}' )" >> $GITHUB_ENV

      - name: Test suffix
        run: |
          echo "in out:" ${{ steps.set-suffix.outputs.image-suffix }}
          echo "in env:" ${{ env.image-suffix }}

      - name: GitHub-SHA-short
        id: sha-short
        run: |
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV

      - name: Test SHA-short
        run: |
          echo "in out: ${{ steps.sha-short.outputs.sha_short }}"
          echo "in env: ${{ env.sha_short }}"

  call_reusable:
    uses: ./.github/workflows/sha-short.yml

  test_reusable:
    runs-on: ubuntu-latest
    steps:
      - name: compare sha
        run: |
          echo "reusable sha-short: " ${{ needs.call_reusable.outputs.sha-short }}
          echo "from env: " ${{ env.sha_short }}
