name: Hello ENV

on:
  workflow_dispatch:

env:
  GLOBAL_ENV: 1
  ANOTHER_ENV: Hi

jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      success: 0
    steps:
      - name: Hello world
        run: |
          echo "Hello world - success is ${{ env.success }}"

      - name: Update success
        id: set-success
        run: |
          echo "success=1" >> $GITHUB_ENV

      - name: Show success
        id: show-success
        run: |
          echo "Hellooo success ${{ env.success }}"

      - name: overwrite GLOBAL_ENV
        id: ovwrt-globalenv
        run: |
          echo "GLOBAL_ENV=11" >> $GITHUB_ENV

      - name: Show globalenv
        id: show-globalenv
        run: |
          echo "Hellooo GLOBAL_ENV ${{ github.env.GLOBAL_ENV }}"
