name: Hello ENV

on:
  workflow_dispatch:

env:
  GLOBAL_ENV: 0
  ANOTHER_ENV: Hi

jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      success: 0
    outputs:
      success-out: 0
    steps:
      - name: Hello world
        run: |
          echo "Hello world - success is ${{ env.success }}"

      - name: Update success
        id: set-success
        run: |
          echo "success=1" >> $GITHUB_ENV

      - name: Show success
        id: show-success
        run: |
          echo "Hellooo success ${{ env.success }}"

      - name: overwrite GLOBAL_ENV
        id: ovwrt-globalenv
        run: |
          echo "GLOBAL_ENV=11" >> $GITHUB_ENV

      - name: Show globalenv
        if: env.GLOBAL_ENV > 0
        id: show-globalenv
        run: |
          echo "Hellooo GLOBAL_ENV ${{ env.GLOBAL_ENV }}"

      - name: Set output
        id: set-out
        run: echo "success-out=${{ env.GLOBAL_ENV }}" >> $GITHUB_OUTPUT

  hello-env-2:
    needs: hello-world
    if: needs.outputs.success-out > 0
    runs-on: ubuntu-latest
    steps:
      - name: last step
        run: echo "Last step got the value ${{ needs.outputs.success-out }}"