name: Hello world

on: 
  workflow_dispatch:
    inputs:
      build-target:
        description: 'The target stage in docker build, "production" is the build-stage.'
        required: true
        # on develop branch we use as default 'production'; For releases we should use 'demo' and push this release to a server that can host the fela-webcore-demo.
        default: 'production'
        type: choice
        options:
          - demo
          - production
          - frontend
          - backend
          - share

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world"
      - name: With output
        id: set-suffix
        run: echo "image-suffix=$([ '${{ github.event.inputs.build-target }}' != 'production' ] && echo '-${{ github.event.inputs.build-target }}' )" >> $GITHUB_OUTPUT
      - name: With env
        id: set-env
        run: echo "image-suffix=$([ '${{ github.event.inputs.build-target }}' != 'production' ] && echo '-${{ github.event.inputs.build-target }}' )" >> $GITHUB_ENV
      - name: Test1
        run: echo ${{ steps.set-suffix.outputs.image-suffix }}
      - name: Test2
        run: echo ${{ env.image-suffix }}
      - name: Github-SHA
        run: echo ${{ github.sha }}
      - name: Github-SHA-Short
        id: sha-short
        run: |
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
      - name: Test3
        run: echo ${{ steps.sha-short.outputs.sha_short }}
