name: short SHA generator

on:
  workflow_call:
    inputs:
      sha-length:
        description: "length of the shortened sha, default 7"
        type: number
        required: false
        default: 7
      branch:
        description: "Optional branch name, needed for scheduled workflows they usally start from main branch but probably builds another branch"
        type: string
        required: false
    outputs:
      short-sha:
        description: "Shorten github.sha to the first 7 characters"
        value: ${{ jobs.shorten.outputs.short-sha }}

jobs:
  shorten:
    name: Generate the short SHA
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.first.outputs.short-sha }}
    steps:
      - id: first
        run: |
          if [ ! -z ${{ inputs.branch }} ]; then
            sha2shorten=$(git log -n 1 --pretty=format:"%H" ${{inputs.branch}})
            echo "sha of branch ${{ inputs.branch }} is: $sha2shorten"
          else
            sha2shorten=${{ github.sha }}
            echo "sha of current branch is: $sha2shorten"
          fi
          echo "short-sha=$(echo $sha2shorten | cut -c1-${{ inputs.sha-length }}) >> $GITHUB_OUTPUT
