name: SHA-short crator

on:
  workflow_call:
    outputs:
      sha-short:
        description: "The first 8 characters of github.sha"
        value: ${{ jobs.sha-short.outputs.sha-short }}

jobs:
  sha-short:
    name: Generate the short SHA
    runs-on: ubuntu-latest
    outputs:
      sha-short: ${{ steps.first.outputs.sha-short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: first
        run: |
          echo "sha-short=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
