name: short SHA generator

on:
  workflow_call:
    inputs:
      sha-length:
        description: "length of the shortened sha, default 7"
        type: number
        required: false
        default: 7
    outputs:
      short-sha:
        description: "Shorten github.sha to the first 7 characters"
        value: ${{ jobs.shorten.outputs.short-sha }}

jobs:
  shorten:
    name: Generate the short SHA
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.first.outputs.short-sha }}
    steps:
      - id: first
        run: |
          echo "short-sha=$(echo ${{ github.sha }} | cut -c1-${{ github.event.inputs.sha-length }})" >> $GITHUB_OUTPUT